base_url = "https://rdk31.com"
title = "rdk31's blog"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

taxonomies = [
    #{name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
theme = "auto"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]